POST http://localhost:8080/users

{
    "name": "John Doe",
    "email": "johndoe@example.com",
    "password": "123456"
}

###

POST http://localhost:8080/users/auth

{
    "email": "johndoe@example.com",
    "password": "123456"
}