basePath: /
host: localhost:8080
info:
  contact:
    email: vtrujillomazza@gmail.com
    name: Vinicius Trujillo Mazza
  description: Product API with auhtentication
  title: Go API Example
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
